export type Permissions =
    | "ADMINISTRATOR"
    | "BAN_MEMBERS"
    | "KICK_MEMBERS"
    | "MANAGE_MESSAGES"
    | "MANAGE_CHANNELS"
    | "MANAGE_ROLES"
    | "MANAGE_NICKNAMES"
    | "SEND_MESSAGES"
    | "READ_MESSAGES"
    | "CHANGE_NICKNAME";
